/// App name "AR Transcribe" refers to augmented-reality-style overlay UI.
abstract final class AppConstants {
  static const defaultTranscriptionLanguage = 'en-US';

  static const supportedAppLocaleCodes = ['en', 'fa', 'ar'];

  /// Nova-3 monolingual + multilingual codes (Deepgram BCP-47).
  static const transcriptionLanguageCodes = [
    'multi',
    'en-US',
    'en-GB',
    'en-AU',
    'en-IN',
    'es',
    'es-419',
    'fr',
    'fr-CA',
    'de',
    'de-CH',
    'it',
    'pt',
    'pt-BR',
    'pt-PT',
    'nl',
    'nl-BE',
    'fa',
    'ar',
    'hi',
    'ru',
    'uk',
    'tr',
    'zh',
    'zh-CN',
    'zh-TW',
    'zh-HK',
    'ja',
    'ko',
    'vi',
    'th',
    'id',
    'ms',
    'tl',
    'pl',
    'cs',
    'sk',
    'hu',
    'ro',
    'bg',
    'hr',
    'sr',
    'bs',
    'sl',
    'mk',
    'be',
    'el',
    'he',
    'sv',
    'da',
    'fi',
    'no',
    'et',
    'lv',
    'lt',
    'ca',
    'bn',
    'gu',
    'kn',
    'mr',
    'ta',
    'te',
    'ur',
  ];

  static Set<String> get deepgramLanguageCodes =>
      transcriptionLanguageCodes.toSet();
}
